# Default values for abrechnung.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# The values are mapped to: https://github.com/SFTtech/abrechnung/blob/master/.env.example

postgresql:
  host: "database"
  user: abrechnung
  name: abrechnung
  # Set the name of an existing kubernetes secret that contains the database password
  existingSecretName: ""
  existingSecretKey: "password"

abrechnung:
  url: http://localhost:8080
  name: abrechnung
  pythonSecret:
    # Set the name of an existing kubernetes secret that contains the secret value
    existingSecretName: ""
    existingSecretKey: "secret"
  port: 8080
  id: default
  registration:
    enabled: false
    validEmailDomains: "sft.lol,sft.mx"
    allowGuestUsers: true
  email:
    address: abrechnungs@sft.lol
    host: mail
    port: 1025
    mode: smtp
    username: abrechnung
    password: abrechnung

image:
  repository: quay.io/abrechnung/api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

frontendImage:
  repository: quay.io/abrechnung/frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: abrechnung.lukasre.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: abrechnung-tls
     hosts:
       - abrechnung.lukasre.ch

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
