# syntax=docker/dockerfile:1.3
FROM docker.io/nginx:stable-alpine
COPY --chown=nginx:nginx frontend/dist/apps/web/ /var/www/abrechnung/
COPY docker/nginx-static /etc/nginx/conf.d/default.conf
COPY --chmod=0755 docker/entrypoint-frontend.sh /docker-entrypoint.d/99-abrechnung.sh
