# syntax=docker/dockerfile:1.3
FROM node:lts as build
ADD frontend/ /build/
RUN cd /build/ && npm install && npx nx build web 

FROM nginx:stable-alpine
COPY --from=build --chown=nginx:nginx /build/dist/apps/web/ /var/www/abrechnung/
COPY --chown=nginx:nginx frontend/apps/web/src/assets/config.json /var/www/abrechnung/config.json
COPY docker/nginx-static /etc/nginx/conf.d/default.conf