# syntax=docker/dockerfile:1.3
FROM node:lts as frontend-dev
COPY --chown=node:node ./ /abrechnung/
USER node
WORKDIR /abrechnung/
RUN npm install
CMD ["npx", "nx", "serve", "web", "--host", "0.0.0.0"]
