# syntax=docker/dockerfile:1.3
FROM python:3.12-alpine as builder
RUN apk add --no-cache build-base libffi-dev
RUN python3 -m venv /opt/abrechnung-venv
ADD . /src
RUN /opt/abrechnung-venv/bin/python3 -m pip install /src

FROM python:3.12-alpine
RUN addgroup -S abrechnung && adduser -S abrechnung -G abrechnung && apk add --no-cache curl
COPY --from=builder /opt/abrechnung-venv/ /opt/abrechnung-venv/
ADD --chmod=644 --chown=abrechnung:abrechnung docker/abrechnung.yaml /etc/abrechnung/abrechnung.yaml
ADD --chmod=755 ./docker/entrypoint.py /
COPY --chown=abrechnung:abrechnung ./docker/crontab /var/spool/cron/crontabs/abrechnung
USER abrechnung
ENTRYPOINT ["/opt/abrechnung-venv/bin/python3", "-u", "/entrypoint.py"]
