# syntax=docker/dockerfile:1.3
FROM node:lts as build
ADD frontend/ /build/
RUN cd /build/ && npm install && npx nx build web 

FROM node:lts as frontend-dev
COPY --chown=node:node frontend/ /frontend/
USER node
WORKDIR /frontend/
RUN npm install
CMD ["npx", "nx", "serve", "web", "--host", "0.0.0.0"]
