# syntax=docker/dockerfile:1.3
FROM docker.io/nginx:stable-alpine
COPY --chown=nginx:nginx frontend/apps/web/ /var/www/abrechnung/
COPY --chown=nginx:nginx frontend/apps/web/src/assets/config.json /var/www/abrechnung/config.json
COPY docker/nginx-static /etc/nginx/conf.d/default.conf
COPY --chown=nginx:nginx --chmod=0750 docker/entrypoint-frontend.sh /docker-entrypoint.d/99-abrechnung.sh
